# Generated by Django 5.1.4 on 2024-12-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('CARTAO_CREDITO', 'Cartão de Crédito'), ('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência Bancária')], max_length=50)),
                ('data_pagamento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='compras.compra')),
            ],
        ),
    ]
